# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Build Debug APK"
  lane :slack_build do
    gradle(task: "assembleDebug")
    upload_to_slack()
  end

  desc "Upload the APK to Slack Channel"
  private_lane :upload_to_slack do |options|
    file_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    file_name = file_path.gsub(/\/.*\//,"")
    access_token = "xoxb-2798899399232-2800146519472-MlLu77er4bnYQ7Qmws5NUvDn"
    channel_name = "apk-file"
    sh "echo Uploading " + file_name + " to Slack"
    sh "curl https://slack.com/api/files.upload -F token=\"" + access_token + "\" -F channels=\"" + channel_name + "\" -F title=\"" + file_name + "\" -F filename=\"" + file_name + "\" -F file=@" + file_path
  end
end
