name: CI workflow

on: [push]

jobs:
  apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Decrypt Services
        run: |
          gpg --quiet --batch --yes --always-trust --decrypt --passphrase=$FIREBASE_SECRET --output services.tar services.tar.gpg
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}

      - name: Unzip Services
        run: tar xvf services.tar

      - name: Access Secrets
        run: |
          echo API_END_POINT=\"$API_END_POINT\" > ./local.properties
        env:
          API_END_POINT: ${{ secrets.API_END_POINT }}

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace