package app.moc.model

import androidx.annotation.Keep

@Keep
data class Business(
        val categoryM: Int,
        val categoryS: Int?,
        val content: String,
        val type: String
){
    companion object {
        const val CATEGORY_MAIN = "main"
        const val CATEGORY_SUB = "sub"
    }
}

val businessMain = listOf(
        Business(categoryM = 1, categoryS = null, content = "IT/인터넷", type = Business.CATEGORY_MAIN),
        Business(categoryM = 2, categoryS = null, content = "경영/기획/컨설팅", type = Business.CATEGORY_MAIN),
        Business(categoryM = 3, categoryS = null, content = "교육", type = Business.CATEGORY_MAIN),
        Business(categoryM = 4, categoryS = null, content = "금융/재무", type = Business.CATEGORY_MAIN),
        Business(categoryM = 5, categoryS = null, content = "디자인", type = Business.CATEGORY_MAIN),
        Business(categoryM = 6, categoryS = null, content = "마케팅/시장조사", type = Business.CATEGORY_MAIN),
        Business(categoryM = 7, categoryS = null, content = "미디어/홍보", type = Business.CATEGORY_MAIN),
        Business(categoryM = 8, categoryS = null, content = "법률/법무", type = Business.CATEGORY_MAIN),
        Business(categoryM = 9, categoryS = null, content = "생산/제조", type = Business.CATEGORY_MAIN),
        Business(categoryM = 10, categoryS = null, content = "생산관리/품질관리", type = Business.CATEGORY_MAIN),
        Business(categoryM = 11, categoryS = null, content = "서비스/고객지원", type = Business.CATEGORY_MAIN),
        Business(categoryM = 12, categoryS = null, content = "엔지니어링", type = Business.CATEGORY_MAIN),
        Business(categoryM = 13, categoryS = null, content = "연구개발", type = Business.CATEGORY_MAIN),
        Business(categoryM = 14, categoryS = null, content = "영업/제휴", type = Business.CATEGORY_MAIN),
        Business(categoryM = 15, categoryS = null, content = "유통/무역", type = Business.CATEGORY_MAIN),
        Business(categoryM = 16, categoryS = null, content = "의약", type = Business.CATEGORY_MAIN),
        Business(categoryM = 17, categoryS = null, content = "인사/총무", type = Business.CATEGORY_MAIN),
        Business(categoryM = 18, categoryS = null, content = "전문직", type = Business.CATEGORY_MAIN),
        Business(categoryM = 19, categoryS = null, content = "특수계층/공공", type = Business.CATEGORY_MAIN),
)

val businessSub = listOf(
        Business(categoryM = 1, categoryS = 101, content = "QA(Quality Assurance)", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 102, content = "프로젝트매니저", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 103, content = "모바일앱개발", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 104, content = "웹개발", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 105, content = "DBA(Database Admin.)", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 106, content = "시스템엔지니어", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 107, content = "소프트웨어엔지니어", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 108, content = "하드웨어엔지니어", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 109, content = "네트워크/보안/운영", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 110, content = "게임개발", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 111, content = "웹퍼블리셔", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 112, content = "기획", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 113, content = "데이터분석", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 114, content = "소프트웨어아키텍트", type = Business.CATEGORY_SUB),
        Business(categoryM = 1, categoryS = 115, content = "ERP", type = Business.CATEGORY_SUB),
        Business(categoryM = 2, categoryS = 201, content = "경영지원", type = Business.CATEGORY_SUB),
        Business(categoryM = 2, categoryS = 202, content = "경영기획/전략", type = Business.CATEGORY_SUB),
        Business(categoryM = 2, categoryS = 203, content = "컨설팅", type = Business.CATEGORY_SUB),
        Business(categoryM = 3, categoryS = 301, content = "교육기획/교재개발", type = Business.CATEGORY_SUB),
        Business(categoryM = 3, categoryS = 302, content = "학습지/과외/방문 교사", type = Business.CATEGORY_SUB),
        Business(categoryM = 3, categoryS = 303, content = "유치원/보육 교사", type = Business.CATEGORY_SUB),
        Business(categoryM = 3, categoryS = 304, content = "초중고/특수학교 교사", type = Business.CATEGORY_SUB),
        Business(categoryM = 3, categoryS = 305, content = "입시/보습/학원 강사", type = Business.CATEGORY_SUB),
        Business(categoryM = 3, categoryS = 306, content = "외국어/어학원 강사", type = Business.CATEGORY_SUB),
        Business(categoryM = 3, categoryS = 307, content = "대학교수", type = Business.CATEGORY_SUB),
        Business(categoryM = 3, categoryS = 308, content = "전문강사", type = Business.CATEGORY_SUB),
        Business(categoryM = 3, categoryS = 309, content = "교직원", type = Business.CATEGORY_SUB),
        Business(categoryM = 4, categoryS = 401, content = "재무기획/재무분석", type = Business.CATEGORY_SUB),
        Business(categoryM = 4, categoryS = 402, content = "회계사", type = Business.CATEGORY_SUB),
        Business(categoryM = 4, categoryS = 403, content = "세무사", type = Business.CATEGORY_SUB),
        Business(categoryM = 4, categoryS = 404, content = "경리/출납/결산 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 4, categoryS = 405, content = "손익/리스크관리", type = Business.CATEGORY_SUB),
        Business(categoryM = 4, categoryS = 406, content = "증권/투자분석가", type = Business.CATEGORY_SUB),
        Business(categoryM = 4, categoryS = 407, content = "외환/국제금융/펀드매니저", type = Business.CATEGORY_SUB),
        Business(categoryM = 4, categoryS = 408, content = "보험계리사/손해사정인", type = Business.CATEGORY_SUB),
        Business(categoryM = 4, categoryS = 409, content = "채권관리", type = Business.CATEGORY_SUB),
        Business(categoryM = 4, categoryS = 410, content = "자산운용가", type = Business.CATEGORY_SUB),
        Business(categoryM = 4, categoryS = 411, content = "은행원", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 501, content = "출판/편집디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 502, content = "광고/시각디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 503, content = "UI/UX/GUI디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 504, content = "브랜드디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 505, content = "그래픽디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 506, content = "캐릭터디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 507, content = "애니메이션디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 508, content = "일러스트레이터", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 509, content = "폰트디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 510, content = "제품/산업디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 511, content = "전시/무대디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 512, content = "영상/모션디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 513, content = "건축/설계디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 514, content = "환경/조경디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 515, content = "패션/섬유디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 516, content = "금속/공예디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 5, categoryS = 517, content = "웹디자인", type = Business.CATEGORY_SUB),
        Business(categoryM = 6, categoryS = 601, content = "마케팅", type = Business.CATEGORY_SUB),
        Business(categoryM = 6, categoryS = 602, content = "전략마케팅", type = Business.CATEGORY_SUB),
        Business(categoryM = 6, categoryS = 603, content = "제품별마케팅", type = Business.CATEGORY_SUB),
        Business(categoryM = 6, categoryS = 604, content = "마케팅커뮤니케이션", type = Business.CATEGORY_SUB),
        Business(categoryM = 6, categoryS = 605, content = "온라인마케팅", type = Business.CATEGORY_SUB),
        Business(categoryM = 6, categoryS = 606, content = "CRM", type = Business.CATEGORY_SUB),
        Business(categoryM = 6, categoryS = 607, content = "브랜드마케팅", type = Business.CATEGORY_SUB),
        Business(categoryM = 6, categoryS = 608, content = "상품개발/기획/MD", type = Business.CATEGORY_SUB),
        Business(categoryM = 6, categoryS = 609, content = "시장조사/분석", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 701, content = "대외협력", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 702, content = "홍보", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 703, content = "방송연출/PD/감독 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 704, content = "진행/아나운서", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 705, content = "배우/모델", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 706, content = "기자", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 707, content = "작가/시나리오 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 708, content = "연예/엔터테인먼트 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 709, content = "영화제작/배급 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 710, content = "공연/무대/스텝 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 711, content = "카메라/조명/미술 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 712, content = "음악/음향/사운드 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 713, content = "사진/포토그래퍼/카메라기자", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 714, content = "인쇄/출판/편집 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 7, categoryS = 715, content = "광고기획/카피라이터", type = Business.CATEGORY_SUB),
        Business(categoryM = 8, categoryS = 801, content = "변호사", type = Business.CATEGORY_SUB),
        Business(categoryM = 8, categoryS = 802, content = "법률/법무", type = Business.CATEGORY_SUB),
        Business(categoryM = 8, categoryS = 803, content = "특허/변리사", type = Business.CATEGORY_SUB),
        Business(categoryM = 8, categoryS = 804, content = "감사", type = Business.CATEGORY_SUB),
        Business(categoryM = 9, categoryS = 901, content = "생산/제조", type = Business.CATEGORY_SUB),
        Business(categoryM = 9, categoryS = 902, content = "포장/조립 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 9, categoryS = 903, content = "금속/금형", type = Business.CATEGORY_SUB),
        Business(categoryM = 9, categoryS = 904, content = "기계/기계설비 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 9, categoryS = 905, content = "전기/전자/제어 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 9, categoryS = 906, content = "반도체/디스플레이", type = Business.CATEGORY_SUB),
        Business(categoryM = 9, categoryS = 907, content = "비금속/요업/신소재 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 9, categoryS = 908, content = "화학/에너지 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 9, categoryS = 909, content = "바이오/제약/식품 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 9, categoryS = 910, content = "안경/렌즈/광학 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 9, categoryS = 911, content = "섬유/의류/패션 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 10, categoryS = 1001, content = "생산관리", type = Business.CATEGORY_SUB),
        Business(categoryM = 10, categoryS = 1002, content = "품질관리", type = Business.CATEGORY_SUB),
        Business(categoryM = 10, categoryS = 1003, content = "공정관리", type = Business.CATEGORY_SUB),
        Business(categoryM = 10, categoryS = 1004, content = "생산/품질기획", type = Business.CATEGORY_SUB),
        Business(categoryM = 10, categoryS = 1005, content = "안전관리", type = Business.CATEGORY_SUB),
        Business(categoryM = 11, categoryS = 1101, content = "고객지원/CS", type = Business.CATEGORY_SUB),
        Business(categoryM = 11, categoryS = 1102, content = "고객지원/Desk", type = Business.CATEGORY_SUB),
        Business(categoryM = 11, categoryS = 1103, content = "스튜어디스/승무원", type = Business.CATEGORY_SUB),
        Business(categoryM = 11, categoryS = 1104, content = "호텔리어", type = Business.CATEGORY_SUB),
        Business(categoryM = 11, categoryS = 1105, content = "여행가이드", type = Business.CATEGORY_SUB),
        Business(categoryM = 11, categoryS = 1106, content = "웨딩플래너/커플매니저", type = Business.CATEGORY_SUB),
        Business(categoryM = 11, categoryS = 1107, content = "뷰티/미용 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 11, categoryS = 1108, content = "의전", type = Business.CATEGORY_SUB),
        Business(categoryM = 11, categoryS = 1109, content = "외식업/식음료", type = Business.CATEGORY_SUB),
        Business(categoryM = 11, categoryS = 1110, content = "기타 서비스직", type = Business.CATEGORY_SUB),
        Business(categoryM = 11, categoryS = 1111, content = "경호/경비원", type = Business.CATEGORY_SUB),
        Business(categoryM = 12, categoryS = 1201, content = "건축설계", type = Business.CATEGORY_SUB),
        Business(categoryM = 12, categoryS = 1202, content = "토목설계", type = Business.CATEGORY_SUB),
        Business(categoryM = 12, categoryS = 1203, content = "기계설계", type = Business.CATEGORY_SUB),
        Business(categoryM = 12, categoryS = 1204, content = "배관설계", type = Business.CATEGORY_SUB),
        Business(categoryM = 12, categoryS = 1205, content = "전기설계", type = Business.CATEGORY_SUB),
        Business(categoryM = 12, categoryS = 1206, content = "공정설계", type = Business.CATEGORY_SUB),
        Business(categoryM = 12, categoryS = 1207, content = "조달", type = Business.CATEGORY_SUB),
        Business(categoryM = 12, categoryS = 1208, content = "환경/안전/보건(ESH)", type = Business.CATEGORY_SUB),
        Business(categoryM = 12, categoryS = 1209, content = "시공/감리/공무", type = Business.CATEGORY_SUB),
        Business(categoryM = 12, categoryS = 1210, content = "조경/도시/인프라", type = Business.CATEGORY_SUB),
        Business(categoryM = 12, categoryS = 1211, content = "유지/수리/정비", type = Business.CATEGORY_SUB),
        Business(categoryM = 13, categoryS = 1301, content = "전기", type = Business.CATEGORY_SUB),
        Business(categoryM = 13, categoryS = 1302, content = "기계", type = Business.CATEGORY_SUB),
        Business(categoryM = 13, categoryS = 1303, content = "전자/반도체", type = Business.CATEGORY_SUB),
        Business(categoryM = 13, categoryS = 1304, content = "제어", type = Business.CATEGORY_SUB),
        Business(categoryM = 13, categoryS = 1305, content = "화학/화공/섬유", type = Business.CATEGORY_SUB),
        Business(categoryM = 13, categoryS = 1306, content = "금속/재료/신소재", type = Business.CATEGORY_SUB),
        Business(categoryM = 13, categoryS = 1307, content = "유전공학/생명/생물", type = Business.CATEGORY_SUB),
        Business(categoryM = 13, categoryS = 1308, content = "식품", type = Business.CATEGORY_SUB),
        Business(categoryM = 13, categoryS = 1309, content = "환경/수질/대기/폐기물", type = Business.CATEGORY_SUB),
        Business(categoryM = 13, categoryS = 1310, content = "인문/사회과학", type = Business.CATEGORY_SUB),
        Business(categoryM = 13, categoryS = 1311, content = "광산", type = Business.CATEGORY_SUB),
        Business(categoryM = 14, categoryS = 1401, content = "국내영업", type = Business.CATEGORY_SUB),
        Business(categoryM = 14, categoryS = 1402, content = "해외영업", type = Business.CATEGORY_SUB),
        Business(categoryM = 14, categoryS = 1403, content = "영업기획/관리/지원", type = Business.CATEGORY_SUB),
        Business(categoryM = 14, categoryS = 1404, content = "기술영업", type = Business.CATEGORY_SUB),
        Business(categoryM = 14, categoryS = 1405, content = "IT/솔루션영업 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 14, categoryS = 1406, content = "의약영업", type = Business.CATEGORY_SUB),
        Business(categoryM = 14, categoryS = 1407, content = "금융/보험영업", type = Business.CATEGORY_SUB),
        Business(categoryM = 14, categoryS = 1408, content = "판매/매장관리", type = Business.CATEGORY_SUB),
        Business(categoryM = 14, categoryS = 1409, content = "텔레마케팅", type = Business.CATEGORY_SUB),
        Business(categoryM = 15, categoryS = 1501, content = "물류/유통/운송", type = Business.CATEGORY_SUB),
        Business(categoryM = 15, categoryS = 1502, content = "구매/자재/재고", type = Business.CATEGORY_SUB),
        Business(categoryM = 15, categoryS = 1503, content = "수출입관리", type = Business.CATEGORY_SUB),
        Business(categoryM = 15, categoryS = 1504, content = "트레이딩", type = Business.CATEGORY_SUB),
        Business(categoryM = 15, categoryS = 1505, content = "프로젝트/자원개발", type = Business.CATEGORY_SUB),
        Business(categoryM = 15, categoryS = 1506, content = "관세사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1601, content = "의사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1602, content = "한의사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1603, content = "치과의사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1604, content = "수의사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1605, content = "약사/한약사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1606, content = "간호사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1607, content = "치기공사/치위생사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1608, content = "물리치료사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1609, content = "임상심리사/임상병리사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1610, content = "방사선사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1611, content = "안경사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1612, content = "영양사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1613, content = "의무기록사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1614, content = "응급구조사", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1615, content = "간호조무사 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 16, categoryS = 1616, content = "간병인", type = Business.CATEGORY_SUB),
        Business(categoryM = 17, categoryS = 1701, content = "인사관리", type = Business.CATEGORY_SUB),
        Business(categoryM = 17, categoryS = 1702, content = "인재개발/교육", type = Business.CATEGORY_SUB),
        Business(categoryM = 17, categoryS = 1703, content = "채용", type = Business.CATEGORY_SUB),
        Business(categoryM = 17, categoryS = 1704, content = "노무", type = Business.CATEGORY_SUB),
        Business(categoryM = 17, categoryS = 1705, content = "조직문화", type = Business.CATEGORY_SUB),
        Business(categoryM = 17, categoryS = 1706, content = "보상", type = Business.CATEGORY_SUB),
        Business(categoryM = 17, categoryS = 1707, content = "헤드헌터", type = Business.CATEGORY_SUB),
        Business(categoryM = 17, categoryS = 1708, content = "총무/사무", type = Business.CATEGORY_SUB),
        Business(categoryM = 17, categoryS = 1709, content = "비서/안내/수행원 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 17, categoryS = 1710, content = "사무보조/문서작성 ", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1801, content = "감정사/평가사/경매사", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1802, content = "통역/번역", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1803, content = "부동산/공인중개사", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1804, content = "사서/문서관리", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1805, content = "문화/예술/스포츠", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1806, content = "요리사/푸드스타일리스트", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1807, content = "제과제빵사", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1808, content = "상담사", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1809, content = "항공기조종사/항해사", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1810, content = "행정사", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1811, content = "프로게이머", type = Business.CATEGORY_SUB),
        Business(categoryM = 18, categoryS = 1812, content = "종교", type = Business.CATEGORY_SUB),
        Business(categoryM = 19, categoryS = 1901, content = "공무원", type = Business.CATEGORY_SUB),
        Business(categoryM = 19, categoryS = 1902, content = "장교/군인/부사관", type = Business.CATEGORY_SUB),
        Business(categoryM = 19, categoryS = 1903, content = "사회복지/요양/봉사", type = Business.CATEGORY_SUB),
)